command = "i3status-rs"

# colors
background = "#2d353bff"
color = "#d3c6aa"
# separator = "#9da9a0"
tag_fg = "#dbbc7f"
tag_bg = "#2d353b"
tag_focused_fg = "#2d353b"
tag_focused_bg = "#a7c080"
tag_urgent_fg = "#2d353b"
tag_urgent_bg = "#e67e80"
tag_inactive_fg = "#dbbc7f"
tag_inactive_bg = "#2d353b"

# font+spacing
font = "Iosevka 10"
tags_padding = 16.0
# jank for volume to not have internal overlap??
# blocks_overlap = -0.2

# positioning
position = "top"
