icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#2D353B"
idle_fg = "#D3C6AA"
good_bg = "#2D353B"
good_fg = "#A7C080"
warning_bg = "#2D353B"
warning_fg = "#E69875"
critical_bg = "#2D353B"
critical_fg = "#E67E80"
info_bg = "#2D353B"
info_fg = "#DBBC7F"
separator_bg = "#2D353B"
separator_fg = "#A7C080"
# separator = ""
# end_separator = ""


[icons]
icons = "awesome4"

[[block]]
block = "packages"
format = " $icon $aur.eng(w:1) "
aur_command = "xbps-install -Mnu"

[[block]]
block = "cpu"

[[block]]
format = " $icon $average "
format_alt = " $icon $average avg, $max max "
block = "temperature"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
interval = 60
format = " $icon $percentage "
format_alt = " $icon $used.eng(w:2)/$total.eng(w:2) "

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
