icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#2D353B"
idle_fg = "#D3C6AA"
good_bg = "#2D353B"
good_fg = "#A7C080"
warning_bg = "#2D353B"
warning_fg = "#E69875"
critical_bg = "#2D353B"
critical_fg = "#E67E80"
info_bg = "#2D353B"
info_fg = "#DBBC7F"
separator_bg = "#2D353B"
separator_fg = "#A7C080"
# separator = ""
# end_separator = ""


[icons]
icons = "awesome4"

[[block]]
block = "music"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/weather.sh"
format = " $text "
interval = 1800

[[block]]
block = "packages"
format = " $icon $pacman.eng(w:1) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
format = " $icon $average "
format_alt = " $icon $average avg, $max max "
block = "temperature"
good = 30
idle = 40
info = 60
warning = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
interval = 60
warning = 80.0
alert = 90.0
format = " $icon $percentage "
format_alt = " $icon $used.eng(w:2)/$total.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "battery"
format = " $icon $percentage {$time |} "
full_format = " $icon $percentage "
not_charging_format = " $icon $percentage "
charging_format = " $icon $percentage "
empty_format = " $icon $percentage "
missing_format = " $icon "
